### ISSUE TITLE
buildout fails

### ISSUE THREAD

**Issue by pabo3000** [taito-zz/collective.cart.core#1]
Getting distribution for 'collective.cart.core'.
Running easy_install:
/home/pab/workspace/python26/src/python-buildout/python-2.6/bin/python "-c" "from setuptools.command.easy_install import main;main()" "-mUNxd" "/home/pab/.buildout/eggs/tmp0LlbpM" "-Z" "-q" "/home/pab/.buildout/downloads/dist/collective.cart.core-0.4.zip"
path=/home/pab/workspace/python26/src/python-buildout/python-2.6/lib/python2.6/site-packages/distribute-0.6.19-py2.6.egg

error: docs/CONTRIBUTORS.txt: No such file or directory
An error occurred when trying to install collective.cart.core 0.4. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'collective.cart.core'.
Error: Couldn't install: collective.cart.core 0.4

**Comment by taito-zz** [comment]
Must be fixed now!
